
FROM nginx:latest

LABEL maintainer="Bayram OZKAN" contact="bbw0r1d"

ENV KULLANICI="bbw0r1d"

ARG RENK

RUN apt-get update && apt-get install -y curl wget htop
  
WORKDIR /gecici

ADD https://wordpress.org/latest.tar.gz . 

WORKDIR /usr/share/nginx/html

COPY html/${RENK} .

HEALTHCHECK --interval=5s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost/ || exit 1

CMD [ "./script.sh" ]


